services:
  mysql:
    image: mysql:8.0
    container_name: exam_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exam_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build: .
    container_name: exam_php
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: exam_db
      DB_USER: root
      DB_PASS: root
    ports:
      - "8080:80"

volumes:
  mysql_data:
